/** Source of truth for the `diagnosis-catalog` Firestore collection — feeds
 * the consultation form's diagnosis search. Extensible; the form also accepts
 * a manually typed diagnosis that is not listed here. */
export const DIAGNOSIS_CATALOG: string[] = [
	'Gastroenteritis',
	'Dermatitis atópica',
	'Dermatitis alérgica por pulgas',
	'Otitis externa',
	'Parasitosis intestinal',
	'Infección respiratoria superior',
	'Enfermedad periodontal',
	'Obesidad',
	'Cojera de origen traumático',
	'Conjuntivitis',
	'Cistitis',
	'Pancreatitis',
	'Enfermedad renal crónica',
	'Diabetes mellitus',
	'Hipotiroidismo',
	'Pioderma',
	'Sarna',
	'Dermatofitosis',
	'Tos de las perreras',
	'Moquillo canino',
	'Parvovirosis',
	'Rinotraqueítis felina',
	'Gingivoestomatitis felina',
	'Úlcera corneal',
	'Fractura',
	'Herida por mordedura',
	'Absceso',
	'Intoxicación',
	'Deshidratación',
];
