export enum Permission {
	CONTACTS_READ = 'contacts:read',
	CONTACTS_UPDATE = 'contacts:update',
	CONTACTS_DELETE = 'contacts:delete',
	USERS_READ = 'users:read',
	USERS_UPDATE = 'users:update',
	PETS_READ = 'pets:read',
	PETS_WRITE = 'pets:write',
	PETS_MANAGE_ALL = 'pets:manage-all',
	SERVICES_WRITE = 'services:write',
	APPOINTMENTS_READ = 'appointments:read',
	APPOINTMENTS_WRITE = 'appointments:write',
	APPOINTMENTS_MANAGE_ALL = 'appointments:manage-all',
	MEDICAL_RECORDS_READ = 'medical-records:read',
	MEDICAL_RECORDS_WRITE = 'medical-records:write',
	MEDICAL_RECORDS_MANAGE_ALL = 'medical-records:manage-all',
	MEDICATIONS_WRITE = 'medications:write',
	ORDERS_READ = 'orders:read',
	ORDERS_WRITE = 'orders:write',
	ORDERS_MANAGE_ALL = 'orders:manage-all',
	REPORTS_READ = 'reports:read',
}
