services:
  frontend:
    image: cabreraevil/dps-vet-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dps-vet-web
    restart: unless-stopped
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    networks:
      - dps_vet_web_net

networks:
  dps_vet_web_net:
    name: dps_vet_web_net
