namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_API_URL: string;
		NEXT_PUBLIC_PROXY?: boolean;
		NEXT_PUBLIC_HOST?: string;
		NEXT_PUBLIC_GOOGLE_ADSENSE_ID: string;
		NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: string;
		NEXT_PUBLIC_GOOGLE_SITES_VERIFICATION: string;
		AUTH_SECRET: string;
		AUTH_DEBUG?: boolean;
		FIREBASE_PROJECT_ID: string;
		FIREBASE_CLIENT_EMAIL: string;
		FIREBASE_PRIVATE_KEY: string;
		FIREBASE_STORAGE_BUCKET: string;
		FIREBASE_DATABASE_URL: string;
		NEXT_PUBLIC_SENTRY_DSN: string;
		SENTRY_PROJECT: string;
		SENTRY_ORG: string;
	}
}
