import { cn } from '@/lib/utils';
import Providers from '@/providers/providers';
import type { Metadata } from 'next';
import { Geist } from 'next/font/google';
import React from 'react';
import './globals.css';

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
	alternates: {
		canonical: 'https://nextjs.org/',
		languages: {
			en: '/',
		},
	},
	authors: [
		{
			name: 'Next.js Team',
			url: 'https://nextjs.org/',
		},
	],
	creator: 'Next.js Team',
	description: 'Generated by create next app',
	keywords: ['Next.js', 'React', 'TypeScript'],
	openGraph: {
		title: 'Create Next App',
		description: 'Generated by create next app',
		url: 'https://nextjs.org/',
		type: 'website',
		images: [
			{
				url: '/banner.webp',
				width: 800,
				height: 600,
				alt: 'Create Next App',
			},
		],
	},
	publisher: 'Next.js Team',
	title: 'Create Next App',
	verification: {
		google: 'google-site-verification=token',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
			className={cn('font-sans', geist.variable)}
		>
			<body className="dark">
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
